### ISSUE TITLE
Create native application built for Windows

### ISSUE THREAD

**Issue by hawka97** [Mica-Technologies/Minecraft-Forge-Launcher#26]

**Comment by rinrincodes** [comment]
This will be revisited soon once we get our Gradle/Maven/other CLI fork of the Mica app builder going. For now we'll mostly focus on the nearly stable macOS builds as that is still top priority to try to get stable right now. Once we get working on those builds, please feel free to reopen this issue. I'm going to be closing it now for the time being.
