### ISSUE TITLE
Fix error with transparent titlebar thrown by NSWindow causing the titlebar text to hide

### ISSUE THREAD

**Issue by rinrincodes** [Mica-Technologies/Minecraft-Forge-Launcher#28]
The following error is thrown in the console immediately after launcher startup. The error goes as the following:

`java[1075:38919] *** WARNING: Textured window <GlassWindow_Normal: 0x7fa9325423d0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
`

This flag must be changed to YES in order for the titlebar text to show and to prevent further rendering problems from happening on the titlebar.

**Comment by hawka97** [comment]
The title bar text hidden is intentional, as the launcher name and title are display on the left side of the launcher now. 

The error you are seeing there is with regards to the titlebar not showing transparent, and should be another issue.

**Comment by hawka97** [comment]
I have made a change in the code to help alleviate the problem with the transparent titlebar in light and dark modes.
