### ISSUE TITLE
Add button to reset runtime in settings

### ISSUE THREAD

**Issue by hawka97** [Mica-Technologies/Minecraft-Forge-Launcher#29]

**Comment by rinrincodes** [comment]
I'm not really sure what you mean by resetting the runtime @hawka97. Do you mean resetting the entire launcher to defaults of resetting most of the modpack's own settings?

**Comment by hawka97** [comment]
fixed

**Comment by hawka97** [comment]
The runtime is the Java 8 JRE that the launcher downloads and manages. It is the Java Runtime Environment that the actual Minecraft game will use.
