### ISSUE TITLE
MCLA modpack keeps redownloading when adding a new modpack to the list on the settings window

### ISSUE THREAD

**Issue by rinrincodes** [Mica-Technologies/Minecraft-Forge-Launcher#31]
Upon adding a new modpack to the modpack list and hitting the enter key on the settings window, another window keeps coming up with the MCLA modpack constantly redownloading all game files.

**Comment by rinrincodes** [comment]
I'm guessing this could be a bug but I'm not sure that it's normally intended for the launcher to do this on each modpack being added to refresh all of the available modpack resources with both the client and the server.

**Comment by hawka97** [comment]
You're correct. This is intended. Each time the list of modpacks is modified, the launcher will perform a verification of each modpack (same as launcher startup). If the verification fails, replacement files are downloaded.
