### ISSUE TITLE
Make resize runtime button smaller, change color to red and add a prompt asking to reset the runtime

### ISSUE THREAD

**Issue by rinrincodes** [Mica-Technologies/Minecraft-Forge-Launcher#36]
The reset runtime button is a bit too big and needs to be shrunken down, change its color to red and have a prompt asking to reset the runtime.

**Comment by rinrincodes** [comment]
Button color has been changed. Not sure if you still want a prompt or not.

**Comment by rinrincodes** [comment]
Referring to PR #38.

**Comment by hawka97** [comment]
4fc9b0a4004d31cf184817b57e1b493b7f98cd7f
