### ISSUE TITLE
Exiting settings while launcher is in full screen makes the launcher hang and controls shift to the top of the screen

### ISSUE THREAD

**Issue by rinrincodes** [Mica-Technologies/Minecraft-Forge-Launcher#37]
As soon as you click the return or save button in the launcher settings, the launcher immediately hangs requiring a force quit to close it and that the controls shift to the top of the screen.

**Comment by rinrincodes** [comment]
This same problem also happens when the main launcher window is in full screen and and you try to go into settings also making the launcher hang mostly due to it not being full screen when the settings window opens.

**Comment by rinrincodes** [comment]
Log out button also does the same thing too and makes the launcher hang while in full screen.

**Comment by hawka97** [comment]
should be fixed now
