### ISSUE TITLE
Add "DANGER ZONE" section

### ISSUE THREAD

**Issue by rinrincodes** [Mica-Technologies/Minecraft-Forge-Launcher#38]
With the addition of the reset runtime button, we now need a dedicated section to have additional reset buttons for modpacks and the launcher.

**Comment by rinrincodes** [comment]
Referring to PR #36.

**Comment by hawka97** [comment]
There isn't much space on the settings window, but I included references to the danger zone when clicking the reset runtime button. That should cover this?

**Comment by hawka97** [comment]
@rinrincodes ? Is the warning that says DANGER ZONE ok?

**Comment by rinrincodes** [comment]
Yes you can go with "DANGER ZONE" as the comment in red text in the launcher settings.

**Comment by hawka97** [comment]
Ok
