### ISSUE TITLE
Make modpack selection dropdown say "No available modpacks!" when there isn't any installed/can't be found

### ISSUE THREAD

**Issue by rinrincodes** [Mica-Technologies/Minecraft-Forge-Launcher#40]
Whenever there is no modpacks currently installed or the launcher is unable to find any modpacks due to errors and such, the modpack selection dropdown comes up with a blank string with nothing in it not really informing the user of what is going on with their modpacks.

**Comment by hawka97** [comment]
fixed in df2e7de2030c5b7ea8117e6be6434060562fa736
