### ISSUE TITLE
Enable window resizing checkbox in settings is still broken

### ISSUE THREAD

**Issue by rinrincodes** [Mica-Technologies/Minecraft-Forge-Launcher#46]
When checking the enable window resizing checkbox in settings, now the checkbox applies the setting to disable window resizing for just a second and then reverts to doing nothing afterwards each time the checkbox is checked.

**Comment by hawka97** [comment]
fixed in 9c458a5390b2456756201caf21a8b0aea2d4d771

**Comment by rinrincodes** [comment]
The checkbox is still partially broken in the 2019.1 release. It works for just a second then goes back to being enabled afterwards. Keeping this open till it is fully fixed.
